# Generated by Django 4.2.5 on 2023-09-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ifood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="delivery",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
