# Generated by Django 4.2.5 on 2023-09-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ifood", "0002_offer_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="star",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
            preserve_default=False,
        ),
    ]
